# Generated by Django 3.0.5 on 2020-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=8)),
                ('tariff', models.CharField(max_length=8)),
                ('quantity', models.SmallIntegerField()),
                ('country', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('office', models.CharField(max_length=20)),
                ('doc_type', models.CharField(max_length=3)),
                ('doc_number', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('line', models.SmallIntegerField()),
                ('location', models.CharField(choices=[('GRE', 'GRENADA'), ('SLU', 'ST. LUCIA')], default='GRE', max_length=3)),
            ],
        ),
    ]
