# Generated by Django 3.0.5 on 2020-05-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=8)),
                ('quantity', models.SmallIntegerField()),
                ('sales_status', models.CharField(max_length=20)),
                ('rec_num', models.CharField(max_length=10)),
                ('sales_date', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ticket_num', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=50)),
                ('id_num', models.CharField(max_length=150)),
                ('vessel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('depart_date', models.CharField(max_length=10)),
                ('depart_port', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customsinventory',
            name='sku',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
