# Generated by Django 3.0.5 on 2020-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bank_bankinfo_payscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.CharField(default='bi-monthly pay', max_length=20),
            preserve_default=False,
        ),
    ]
