# Generated by Django 3.0.5 on 2020-09-23 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EarningsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='WageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrol.WageInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('earnings_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrol.EarningsType')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrol.WageDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrol.DeductionType')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrol.WageDetails')),
            ],
        ),
    ]
