# Generated by Django 3.0.5 on 2020-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
