# Generated by Django 3.0.5 on 2020-04-24 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200409_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='sku',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='internalsku',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stone',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_ID', models.SmallIntegerField(unique=True)),
                ('location', models.CharField(choices=[('GRE', 'GRENADA'), ('SLU', 'ST. LUCIA')], default='SLU', max_length=3)),
                ('warehousing', models.SmallIntegerField()),
                ('invoice_number', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('awb', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('CUS', 'AWAITING CUSTOMS'), ('COM', 'COMPLETED')], default='PEN', max_length=3)),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('entered_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('racked_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_types', to='inventory.ShipmentType')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Shipper')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier')),
            ],
            options={
                'ordering': ('batch_ID',),
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Entries', to='inventory.Entry'),
            preserve_default=False,
        ),
    ]
