# Generated by Django 3.0.5 on 2020-04-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200424_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='sku',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='awb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together={('sku', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['sku'], name='inventory_c_sku_13e43b_idx'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Country'),
            preserve_default=False,
        ),
    ]
