# Generated by Django 3.0.5 on 2020-05-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_entry_serialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='introduced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='country',
            field=models.ForeignKey(default='US', on_delete=django.db.models.deletion.CASCADE, to='inventory.Country'),
        ),
    ]
