# Generated by Django 3.0.5 on 2020-05-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200501_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='country',
            field=models.ForeignKey(default=238, on_delete=django.db.models.deletion.CASCADE, to='inventory.Country'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
