# Generated by Django 3.0.5 on 2020-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200504_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='shipper',
            options={'ordering': ('shipper',)},
        ),
        migrations.AlterModelOptions(
            name='stone',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('code',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight in (KG)'),
        ),
    ]
