# Generated by Django 3.0.5 on 2020-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200507_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
