# Generated by Django 3.0.5 on 2020-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200511_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='internalsku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
