# Generated by Django 3.0.5 on 2020-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200512_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='internalsku',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
