# Generated by Django 3.0.5 on 2020-05-12 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200512_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='internalsku',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
