# Generated by Django 3.0.5 on 2020-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20200512_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
